In [3]:
import warp as wp
import numpy as np

wp.init()

@wp.kernel
def test(A: wp.mat33, x: wp.vec3, y: wp.array(dtype = wp.vec3)):
    y[0] = A @ x
    A[0, 1] = 1.0
    y[1] = A[0]
y = wp.zeros(2, dtype = wp.vec3)

A = wp.zeros(1, dtype = wp.mat33)

@wp.kernel
def t2(A: wp.array(dtype = wp.mat33)):
    A[0] = wp.outer(wp.vec3(1.0), wp.vec3(1.0, 2.0, 3.0))


# wp.launch(test, (1), inputs = [wp.diag(wp.vec3(1.0)), wp.vec3(1.0, 1.0, 1.0), y])
wp.launch(t2, 1, inputs = [A])

Module __main__ load on device 'cuda:0' took 21.85 ms


In [6]:

import warp as wp
wp.init()
@wp.kernel
def test1() -> int:
    return 1

a = 0
wp.launch(test1, (1))
print(a)

Module __main__ 19d0de8 load on device 'cuda:0' took 0.19 ms


AttributeError: 'tuple' object has no attribute 'ctype'

In [6]:
vec5i = wp.types.vector(length = 5, dtype = int)
print(vec5i(0, 1, 2, 3, 4))
@wp.kernel
def test2():
    a = vec5i(0, 1, 2, 3, 4)
    print(a)

[0, 1, 2, 3, 4]


In [1]:
import fc_viewer as fc
a = fc.fast_cd_viewer()
import numpy as np
v = np.eye(3)
f = np.arange(3)
# a.set_mesh(v, f, 0)
a.launch()

: 

In [3]:
import warp as wp
wp.init()
mat34 = wp.types.matrix(shape = (3, 4), dtype = float)
a = wp.zeros(1, dtype = mat34)
@wp.kernel
def test(ret: wp.array(dtype = mat34)): 
    a =  mat34(1.0, 2.0, 3.0, 4.0,
                5.0, 6.0, 7.0, 8.0,
                9.0, 10.0, 11.0, 12.0)
    a0 = wp.vec4(1.0, 2.0, 3.0, 4.0)
    a1 = wp.vec4(5.0, 6.0, 7.0, 8.0)
    a2 = wp.vec4(9.0, 10.0, 11.0, 12.0)
    a = mat34(a0, a1, a2)
    print(a)
    ret[0] = a

wp.launch(test, 1, inputs = [a])
print(a.numpy())

Module __main__ 8bb0e0c load on device 'cuda:0' took 0.84 ms


RuntimeError: Error while parsing function "test" at C:\Users\shay\AppData\Local\Temp\ipykernel_27008\1249133514.py:13:
    a = mat34(a0, a1, a2)
;incompatible number of column vectors given (3) when constructing a matrix of shape (3, 4)

In [3]:
import warp as wp
from warp.types import vector
wp.init()
vec5i = vector(length = 5, dtype = int)

In [4]:
A.numpy()

array([[[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]]], dtype=float32)

In [15]:
y.numpy()

array([[1., 1., 1.],
       [1., 1., 0.]], dtype=float32)

In [4]:
import warp as wp

wp.init()
a = wp.mat33(wp.vec3(1.0), wp.vec3(2.0),wp.vec3(3.0))
# print(a)
# print(a[1])

@wp.kernel
def test():
    A = wp.mat33(wp.vec3(1.0), wp.vec3(2.0),wp.vec3(3.0))
    print(A[0])

wp.launch(test,(1))

Module __main__ 2c506af load on device 'cuda:0' took 2.77 ms  (cached)


In [6]:
import warp as wp
wp.init()
@wp.kernel
def test(c: wp.array(dtype = wp.vec3)):
    a = wp.vec3(1.0, 2.0, 3.0)
    b = wp.vec3(3.0, 1.0, 2.0)
    c[0] = (wp.max(a, b))

c = wp.zeros(1, dtype = wp.vec3)
b = wp.zeros(1, dtype = wp.mat33)
wp.launch(test,(1), inputs = [c])

@wp.kernel
def test2(b: wp.array(dtype = wp.mat33)):
    a = wp.mat33(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0)

    print(a)
    b[0] = a
# print(c.numpy())
wp.launch(test2, (1), inputs = [b])
print(b.numpy())

Module __main__ 12360c3 load on device 'cuda:0' took 0.68 ms  (cached)
Module __main__ 12360c3 load on device 'cuda:0' took 0.76 ms  (cached)
[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
